name: Deploy Dev

on:
  workflow_dispatch:

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - name: Get sources
      uses: actions/checkout@v3

    - name: Set themes matrix
      id: set-matrix
      run: |
        themes_json=`cat ./packages/metadata/themes.json`
        themes_json="${themes_json//$'\n'/''}"
        themes_json="${themes_json//$'\r'/''}"
        themes_json="${themes_json//$' '/''}"
        echo "matrix=$themes_json" >> $GITHUB_OUTPUT
  build:
    needs: set-matrix
    name: Build applications
    runs-on: ubuntu-latest
    env:
      CI: false
    strategy:
      matrix:
        theme: ${{fromJson(needs.set-matrix.outputs.matrix)}}
        mode: [ default ]

    steps:
      #Build Devextreme latest
    - name: Get sources
      uses: actions/checkout@v3

    - name: Clone devextreme repo
      run: |
        BASE_BRANCH=$(node -p -e "require('./package.json').version.slice(0, 4).replace('.', '_')")
        test -d ./devextreme-repo || git clone -b 23_2 https://github.com/devexpress/devextreme ./devextreme-repo

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: '18.16.1'

    - name: DevExtreme - Install packages
      working-directory: ./devextreme-repo
      run: npm install --no-audit --no-fund

    - name: DevExtreme - Build
      working-directory: ./devextreme-repo/packages/devextreme
      run: npm run build-npm-devextreme

    - name: DevExtreme - Pack
      working-directory: ./devextreme-repo/packages/devextreme/artifacts/npm/devextreme
      run: npm pack

    - name: DevExtreme dist - Pack
      working-directory: ./devextreme-repo/packages/devextreme/artifacts/npm/devextreme-dist
      run: npm pack

    - name: DevExtreme React - Build
      working-directory: ./devextreme-repo/packages/devextreme-react
      run: npm run pack

    - name: Install devextreme package for React
      shell: bash
      working-directory: ./packages/react
      run: npm install $(find ../../devextreme-repo/packages/devextreme/artifacts/npm/devextreme/ -maxdepth 1 -name "devextreme-*.tgz")

    - name: Install devextreme-dist package for React
      shell: bash
      working-directory: ./packages/react
      run: npm install $(find ../../devextreme-repo/packages/devextreme/artifacts/npm/devextreme-dist/ -maxdepth 1 -name "devextreme-*.tgz")

    - name: Install devextreme-react package for React
      shell: bash
      working-directory: ./packages/react
      run: npm install $(find ../../devextreme-repo/packages/devextreme-react/npm/ -maxdepth 1 -name "devextreme-*.tgz")

      #Build UI Template Gallery
    - name: Get sources
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Set NPM version
      run: npm i npm@7 -g

    - name: Restore npm cache
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Run npm install
      run: npm install

    - name: Set theme
      run: npm run set-theme -- ${{ matrix.theme }}

    - name: Set embedded mode
      if: ${{ matrix.mode == 'embedded' }}
      run: npm run make-embedded-mode

    - name: Build
      run: npm run build

    - name: Copy apps
      run: npm run copy-build -- ${{ matrix.mode }} ${{ matrix.theme }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: devextreme-ui-template-gallery-with-fluent/

  deploy:
    name: Deploy
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - name: Get sources
      uses: actions/checkout@v3

    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: build-artifacts
        path: devextreme-ui-template-gallery-with-fluent

    - name: Deploy in gh-pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: devextreme-ui-template-gallery-with-fluent
        target-folder: .